### ISSUE TITLE
Debian configuration too strict

### ISSUE THREAD

**Issue by jsf9k** [cisagov/ansible-role-automated-security-updates#24]
# 🐛 Summary #

@bra1ncramp noticed that some security updates were not being applied to Debian systems.  Upon investigation, I found that these "missing" security updates come from a package repository with a codename of the form `${distro_codename}-updates`, and therefore they are currently being excluded from `unattended-upgrades` because the package repository codename is specified too strictly in this line:
https://github.com/cisagov/ansible-role-automated-security-updates/blob/a181e93b3e39f00f89402f0d3368ad431e705bd3/tasks/Debian.yml#L24

**Comment by bra1ncramp** [comment]
The change above appeared to have worked
